I'm sorry, but an uncaught exception occurred.

While running game code:
  File "script.rpy", line 24, in script
    scene bg slide_00003_frag_00000 with fitscreen
Exception: Parameter 'new_widget' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "script.rpy", line 24, in script
    scene bg slide_00003_frag_00000 with fitscreen
  File "/home/guichristmann/Programming/Ren'Py/renpy-7.1.3-sdk/renpy/ast.py", line 1356, in execute
    renpy.exports.with_statement(trans, paired)
  File "/home/guichristmann/Programming/Ren'Py/renpy-7.1.3-sdk/renpy/exports.py", line 1481, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "/home/guichristmann/Programming/Ren'Py/renpy-7.1.3-sdk/renpy/display/core.py", line 2227, in do_with
    clear=clear)
  File "/home/guichristmann/Programming/Ren'Py/renpy-7.1.3-sdk/renpy/display/core.py", line 2672, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "/home/guichristmann/Programming/Ren'Py/renpy-7.1.3-sdk/renpy/display/core.py", line 3012, in interact_core
    new_widget=layers_root)
  File "/home/guichristmann/Programming/Ren'Py/renpy-7.1.3-sdk/renpy/atl.py", line 433, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'new_widget' is not known by ATL Transform.

Linux-4.15.0-46-generic-x86_64-with-debian-buster-sid
Ren'Py 7.1.3.1092
Lectures with Prof. JB 1.0
Thu Mar 21 07:19:24 2019
